KDTFinalPJT/books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path("", views.onboarding, name="onboarding"),
    path("main/", views.main, name="main"),
    path("books/", views.index, name="index"),
    path("books/<int:pk>/detail/", views.detail, name="detail"),
    path("books/<int:book_pk>/like/", views.like, name="like"),
    path("search/", views.search, name="search"),
]

KDTFinalPJT/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("books.urls")),
    path("accounts/", include("accounts.urls")),
    path("notices/", include("notices.urls")),
    path("reviews/", include("reviews.urls")),
    path("groups/", include("groups.urls")),
    path("backend_test/", include("backend_test.urls")),
    path("nav/", views.nav, name="nav"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KDTFinalPJT/groups/urls.py
from django.urls import path
from . import views

app_name = "groups"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/like/", views.like, name="like"),
    path("<int:pk>/group_closed/", views.group_closed, name="group_closed"),
]

KDTFinalPJT/groups/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator


class Group(models.Model):
    title = models.CharField(max_length=100)
    introduce = models.TextField(max_length=400)
    place = models.CharField(max_length=200)
    meeting_date = models.DateTimeField()
    number = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    end_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    like_user = models.ManyToManyField(get_user_model(), related_name="like_group")
    image = models.ImageField()
    closed = models.BooleanField(default=False)

KDTFinalPJT/groups/forms.py
from django import forms
from .models import Group


class DateInput(forms.DateInput):
    input_type = "date"


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = [
            "title",
            "introduce",
            "place",
            "number",
            "meeting_date",
            "end_date",
            "image",
            "closed",
        ]

        labels = {
            "title": "모임 제목",
            "introduce": "소개글",
            "place": "주소",
            "number": "모집인원",
            "meeting_date": "모임날짜",
            "end_date": "마감일",
            "image": "이미지",
            "closed": "마감버튼",
        }
        widgets = {
            "meeting_date": DateInput(),
            "end_date": DateInput(),
        }

KDTFinalPJT/groups/views.py
from django.shortcuts import render, redirect
from .models import Group
from .forms import GroupForm
from django.http import JsonResponse
from django.http import HttpResponseForbidden
from django.contrib.auth.decorators import login_required

# Create your views here.

# 모임 페이지
def index(request):
    groups = Group.objects.order_by("-pk")
    ing_groups = Group.objects.filter(closed=0)
    end_groups = Group.objects.filter(closed=1)
    context = {
        "groups": groups,
        "ing_groups": ing_groups,
        "end_groups": end_groups,
    }
    return render(request, "groups/index.html", context)


# 모임 생성
@login_required
def create(request):
    print(request.POST)
    if request.user.is_authenticated:
        if request.method == "POST":
            group_form = GroupForm(request.POST, request.FILES)
            if group_form.is_valid():
                book_review = group_form.save(commit=False)
                book_review.user = request.user
                book_review.save()
                return redirect("groups:index")
        else:
            group_form = GroupForm()
        context = {"group_form": group_form}
        return render(request, "groups/create.html", context)


# 모임 디테일
def detail(request, pk):
    group = Group.objects.get(pk=pk)
    place = group.place
    like_count = group.like_user.count()
    group_like_user = group.like_user
    if like_count >= group.number:
        group.closed = True
        group.save()

    context = {
        "group": group,
        "place": place,
        "like_count": like_count,
        "group_like_user": group_like_user,
    }
    return render(request, "groups/detail.html", context)


# 모임 업데이트
@login_required
def update(request, pk):
    group = Group.objects.get(pk=pk)
    if request.user == group.user:
        if request.method == "POST":
            group_form = GroupForm(request.POST, request.FILES, instance=group)
            if group_form.is_valid():
                group_form.save()
                return redirect("groups:detail", pk)
        else:
            group_form = GroupForm(instance=group)
        context = {
            "group_form": group_form,
            "group": group,
        }
        return render(request, "groups/create.html", context)
    else:
        return HttpResponseForbidden()


# 모임 삭제
@login_required
def delete(request, pk):
    group = Group.objects.get(pk=pk)
    if request.user == group.user:
        group.delete()
        return redirect("groups:index")
    else:
        return HttpResponseForbidden()


# 모집 신청
@login_required
def like(request, pk):
    if request.user.is_authenticated:
        group = Group.objects.get(pk=pk)
        if group.like_user.filter(pk=request.user.pk).exists():
            group.like_user.remove(request.user)
            is_liked = False
        else:
            group.like_user.add(request.user)
            is_liked = True
    else:
        return redirect("groups:detail", pk)
    context = {
        "is_liked": is_liked,
        "like_count": group.like_user.count(),
    }

    return JsonResponse(context)


# 모집마감
def group_closed(request, pk):
    if request.user.is_authenticated:
        group = Group.objects.get(pk=pk)
        if group.closed == False:
            group.closed = True
            group.save()
        else:
            group.closed = False
            group.save()
        return redirect("groups:detail", pk)
    else:
        return redirect("groups:detail", pk)

KDTFinalPJT/groups/templates/groups/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
{% include 'nav.html' %}

<div class="container groups-create">
  <form class="groups-create-form p-5" name="groups_form" onsubmit="return numberCheck2();" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% if request.resolver_match.url_name == 'create' %}  
    <h4 class="text-center mb-4">모임 생성</h4>
    {% else %}
    <h4 class="text-center mb-4">모임 수정</h4>
    {% endif %}
    <div class="row">
      <div class="col-12 col-md-6 groups-form-input">
        <div class="mb-3">
          <label class="form-label" for="id_title">모임 제목</label>
          <input type="text" onkeyup="check_length(this);" name="title" maxlength="101" class="form-control" placeholder="모임 제목" required="" id="id_title"
            value="{{group.title}}">
        </div>
        <div class="mb-3">
          <label class="form-label" for="id_introduce">소개글</label>
          <textarea name="introduce" onkeyup="check_length2(this);" cols="40" rows="13" class="form-control" placeholder="소개글" required="" id="id_introduce">{{group.introduce}}</textarea>
        </div>
        <div class="mb-3">
          <label class="form-label" for="id_number">모집인원</label>
          <input onblur="numberCheck();" type="number" name="number" class="form-control" placeholder="모집인원" required="" id="id_number"
            value="{{group.number}}">
        </div>
        <div class="mb-3">
          <label class="form-label" for="id_image">이미지</label>
          <input type="file" name="image" accept="image/*" class="form-control" required="" id="id_image">
        </div>
      </div>
      <div class="col-12 col-md-6 groups-form-input">
        <!-- Group map -->
        <div class="group-form-map mb-3" id="map"></div>
        <div class="mb-3">
          <label class="form-label" for="id_place">주소</label>
          <input onblur="onblur_event();" type="text" name="place" maxlength="200" class="form-control" placeholder="주소" required="" id="id_place"
            value="{{group.place}}">
        </div>
        <div class="mb-3">
          <label class="form-label" for="id_end_date">모집 마감일</label>
          {% if group.end_date %}
            <input type="text" name="end_date" class="datetimepick form-control" placeholder="기존 날짜:{{ group.end_date }}" required="" id="id_end_date"
             autocomplete="off"> 
          {% else %}
            <input type="text" name="end_date" class="datetimepick form-control" placeholder="모집 마감일을 입력해주세요." required="" id="id_end_date"
             autocomplete="off">
          {% endif %}
        </div>
        <div class="mb-3">
          <label class="form-label" for="id_meeting_date">모임 날짜</label>
          {% if group.meeting_date %} 
            <input type="text" name="meeting_date" class="datetimepick form-control" placeholder="기존 날짜:{{ group.meeting_date }}" required="" id="id_meeting_date"
             autocomplete="off">
          {% else %}
            <input type="text" name="meeting_date" class="datetimepick form-control" placeholder="독서모임 날짜를 입력해주세요." required="" id="id_meeting_date"
             autocomplete="off">
          {% endif %}
        </div>
      </div>
    </div>
    <!-- sumbit -->
    <input class="btn btn--main--reverse w-100 mb-3" type="submit" value="등록하기">
  </form>
</div>

{% endblock content %}

{% block js %}
  <script>
    datePickerSet($("#id_end_date"), $("#id_meeting_date"), true); //다중은 시작하는 달력 먼저, 끝달력 2번째

    /*
    * 달력 생성기
    * @param sDate 파라미터만 넣으면 1개짜리 달력 생성
    * @example   datePickerSet($("#datepicker"));
    * 
    * 
    * @param sDate, 
    * @param eDate 2개 넣으면 연결달력 생성되어 서로의 날짜를 넘어가지 않음
    * @example   datePickerSet($("#datepicker1"), $("#datepicker2"));
    */

  function datePickerSet(sDate, eDate, flag) {
    //시작 ~ 종료 2개 짜리 달력 datepicker	
    if (!isValidStr(sDate) && !isValidStr(eDate) && sDate.length > 0 && eDate.length > 0) {
      var sDay = sDate.val();
      var eDay = eDate.val();

      if (flag && !isValidStr(sDay) && !isValidStr(eDay)) { //처음 입력 날짜 설정, update...			
          var sdp = sDate.datepicker().data("datepicker");
          sdp.selectDate(new Date(sDay.replace(/-/g, "/")));  //익스에서는 그냥 new Date하면 -을 인식못함 replace필요

          var edp = eDate.datepicker().data("datepicker");
          edp.selectDate(new Date(eDay.replace(/-/g, "/")));  //익스에서는 그냥 new Date하면 -을 인식못함 replace필요
      }

      //시작일자 세팅하기 날짜가 없는경우엔 제한을 걸지 않음
      if (!isValidStr(eDay)) {
          sDate.datepicker({
              minDate: new Date(),
              maxDate: new Date(eDay.replace(/-/g, "/")),
              timepicker: true,
              timeFormat: "hh:ii",
          });
      }
      sDate.datepicker({
          minDate: new Date(),
          language: 'ko',
          autoClose: true,
          timepicker: true,
          timeFormat: "hh:ii",
          onSelect: function () {
              datePickerSet(sDate, eDate);
          }
      });

      //종료일자 세팅하기 날짜가 없는경우엔 제한을 걸지 않음
      if (!isValidStr(sDay)) {
          eDate.datepicker({
            minDate: new Date(sDay.replace(/-/g, "/")),
            timepicker: true,
            timeFormat: "hh:ii",
          });
      }
      eDate.datepicker({
          language: 'ko',
          autoClose: true,
          timepicker: true,
          timeFormat: "hh:ii",
          onSelect: function () {
              datePickerSet(sDate, eDate);
          }
      });

      //한개짜리 달력 datepicker
    } else if (!isValidStr(sDate)) {
      var sDay = sDate.val();
      if (flag && !isValidStr(sDay)) { //처음 입력 날짜 설정, update...			
          var sdp = sDate.datepicker().data("datepicker");
          sdp.selectDate(new Date(sDay.replace(/-/g, "/"))); //익스에서는 그냥 new Date하면 -을 인식못함 replace필요
      }

      sDate.datepicker({
          language: 'ko',
          autoClose: true,
          
      });
    }

    function isValidStr(str) {
      if (str == null || str == undefined || str == "")
          return true;
      else
          return false;
    }
  }
  </script>

  <!--여기부터 지도-->
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
  <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=ac496d224ad8e6aeb9687fa6abedb0fd&libraries=services"></script>
  <script>
      // 지도 생성
      var mapContainer = document.getElementById('map'),
      mapOption = {
        center: new kakao.maps.LatLng(33.450701, 126.570667),
        level: 3
      };
      var map = new kakao.maps.Map(mapContainer, mapOption); 

      // 수정 때 이전 장소 마커 불러오기
      var geocoder = new kakao.maps.services.Geocoder();
      var last_place = document.querySelector("#id_place").value
      console.log(last_place)
      // 주소로 좌표를 검색합니다
      geocoder.addressSearch(`${last_place}`, function (result, status) {
        // 정상적으로 검색이 완료됐으면
        if (status === kakao.maps.services.Status.OK) {
          var coords = new kakao.maps.LatLng(result[0].y, result[0].x);
          // 결과값으로 받은 위치를 마커로 표시합니다
          var marker = new kakao.maps.Marker({map: map, position: coords});
          // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
          map.setCenter(coords);
        }
      });
  
      // 장소 입력 input에서 포커스가 떠났을 때 마커 이동하기
      function onblur_event() {
        var geocoder = new kakao.maps.services.Geocoder();
        var place = groups_form.place.value
        console.log(place)
        // 주소로 좌표를 검색합니다
        geocoder.addressSearch(`${place}`, function (result, status) {
          // 정상적으로 검색이 완료됐으면
          if (status === kakao.maps.services.Status.OK) {
            var coords = new kakao.maps.LatLng(result[0].y, result[0].x);
            // 결과값으로 받은 위치를 마커로 표시합니다
            var marker = new kakao.maps.Marker({map: map, position: coords});
            // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
            map.setCenter(coords);
          }
          // 이상한 주소 입력 시 
          else {
            // Sweet alert
            Swal.fire({
              icon: 'question',
              iconHtml: '!',
              title: '올바른 주소를 입력해주세요!',
              text: '지번 주소 또는 도로명 주소가 필요합니다',
              confirmButtonColor: '#92B4EC',
            })
          }
        });
      }
  </script>

  <script>
    function check_length(area) {
      var text = area.value;
      var text_length = text.length;

      if(text_length > 100) {
        // Sweet alert
        Swal.fire({
          icon: 'question',
          iconHtml: '!',
          title: '너무 길어요!',
          text: '100자 이내로 작성해주세요!',
          confirmButtonColor: '#92B4EC',
        })
        text = text.substr(0, 100);
        area.value = text;
        area.focus();
      }
    }
  </script>

  <script>
    function check_length2(area) {
      var text = area.value;
      var text_length = text.length;

      if(text_length > 200) {
        // Sweet alert
        Swal.fire({
          icon: 'question',
          iconHtml: '!',
          title: '너무 길어요!',
          text: '200자 이내로 작성해주세요!',
          confirmButtonColor: '#92B4EC',
        })
        text = text.substr(0, 200);
        area.value = text;
        area.focus();
      }
    }
  </script>

  <script>
    // 모집인원이 양수 이상인지 확인
    function numberCheck() {
      // 공백일 때
      if (groups_form.number.value.length == 0) {
        // Sweet alert
        Swal.fire({
          icon: 'question',
          iconHtml: '!',
          title: '모집인원을 입력해주세요!',
          text: '1명 이상을 모집해주세요!',
          confirmButtonColor: '#92B4EC',
        })
        groups_form.number.value = 1
        groups_form.number.focus();
      }
      // 음수이면
      if(groups_form.number.value <= 0) {
        // Sweet alert
        Swal.fire({
            icon: 'question',
            iconHtml: '!',
            title: groups_form.number.value+'명을 모집할 수는 없어요...',
            text: '1명 이상을 모집해주세요!',
            confirmButtonColor: '#92B4EC',
        })
        groups_form.number.value = 1
        groups_form.number.focus();
      }
    }
  </script>

  <script>
    // 모집인원이 양수 이상인지 확인
    function numberCheck2() {
      // 공백일 때
      if (groups_form.number.value.length == 0) {
        // Sweet alert
        Swal.fire({
          icon: 'question',
          iconHtml: '!',
          title: '모집인원을 입력해주세요!',
          text: '1명 이상을 모집해주세요!',
          confirmButtonColor: '#92B4EC',
        })
        groups_form.number.value = 1
        groups_form.number.focus();
        return false;
      }
      else {
        // 음수이면
        if(groups_form.number.value <= 0) {
          // Sweet alert
          Swal.fire({
              icon: 'question',
              iconHtml: '!',
              title: groups_form.number.value+'명을 모집할 수는 없어요...',
              text: '1명 이상을 모집해주세요!',
              confirmButtonColor: '#92B4EC',
          })
          groups_form.number.value = 1
          groups_form.number.focus();
          return false;
        }
        else {
          return true;
        }
      }
    }
  </script>

{% endblock js %}

KDTFinalPJT/groups/templates/groups/index.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}

<!--모임 목록 템플릿입니다-->

<div class="container group_index">
  <div class="group_index_introduction">
    <h3> 모임 목록 </h3>
    <p> 기록가들의 모임에 참여해 보세요. </p>
  </div>

  <!--모임중/ 모집 마감 선택 -->
  <div class="tab-area">
    <!-- 탭 메뉴 -->
    <input type="radio" name="tabs" id="tab1" checked>
    <label for="tab1">전체 모임</label>
    <input type="radio" name="tabs" id="tab2">
    <label for="tab2">모집 중</label>
    <input type="radio" name="tabs" id="tab3">
    <label for="tab3">모집 마감 </label>

    <!-- 탭1 : 모집중 -->
    <div id="content1" class="tab-content d-flex justify-content-center">
      <!-- 모임 생성 버튼 -->
      <a class="btn btn--main tab-create-btn my-3" href="{% url 'groups:create' %}">모임 생성</a>
      <!-- 전체 모임 리스트 -->
      <div class="row gx-5 w-100">
        <!-- 반복문 시작 -->
        {% for group in groups %}
        <div class="col-12 col-md-6 col-lg-3 group-index-item" style="cursor: pointer;"
          onclick="location.href='{% url 'groups:detail' group.pk %}';">
          <div class="card w-100 mb-5 mx-auto">
            <div class="card-image" style="height: 250px;">
              <img src="{{ group.image.url }}" class="card-img-top" alt="metting-image" style="height: 100%;">
            </div>
            <div class="card-body">
              <p class="card-title" style="margin-bottom: 10px;overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 1;
              -webkit-box-orient: vertical; font-weight: 600;">{{ group.title }}</p>
              <p class="card-text" style="font-size: 14px; color: var(--gray-dark-color);">장소: {{ group.place }} <br>인원: {{ group.number }}명 <br> 
                일시: {{ group.meeting_date|date:"m.d A h:i" }} <br> 모집 마감일: {{ group.end_date |date:"m.d A h:i" }}까지</p>
            </div>
          </div>
        </div>
        {% empty %}
        <div class="my-5 d-flex flex-column align-items-center" style="min-height: 250px;">
          <p style="color: var(--gray-dark-color);">책:오의 첫 모임 주인공이 되어주세요!</p>
        </div>
        {% endfor %}
        <!-- 반복문 끝 -->
      </div>
      <!-- 탭2 : 모집 중 -->
    </div>
    <div id="content2" class="tab-content d-flex justify-content-center">
      <!-- 모집중 모임 리스트 -->
      <div class="row gx-5 w-100">
        <!-- 반복문 시작 -->
        {% for group in ing_groups %}
        <div class="col-12 col-md-6 col-lg-3 group-index-item" style="cursor: pointer;"
          onclick="location.href='{% url 'groups:detail' group.pk %}';">
          <div class=" card w-100 mb-5 mx-auto">
            <div class="card-image position-relative" style="height: 250px;">
              <span class="p-2 badge rounded-pill text-bg-success">모집중</span>
              <img src="{{ group.image.url }}" class="card-img-top" alt="metting-image" style="height: 100%;">
        
            </div>
            <div class="card-body">
              <p class="card-title" style="margin-bottom: 10px; overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 1;
              -webkit-box-orient: vertical; font-weight: 600;">{{ group.title }}</p>
              <p class="card-text" style="font-size: 14px; color: var(--gray-dark-color);"> 장소: {{ group.place }} <br>인원: {{ group.number }}명 <br> 일시: {{ group.meeting_date|date:"m.d(l) A h:i" }} <br> 모집 마감일: {{ group.end_date |date:"m.d A h:i" }}까지</p>
            </div>
          </div>
        </div>
        {% empty %}
        <div class="my-5 d-flex flex-column align-items-center" style="min-height: 250px;">
          <p style="color: var(--gray-dark-color);">모집중인 모임이 없어요</p>
        </div>
        {% endfor %}
        <!-- 반복문 끝 -->
      </div>
    </div>
    <!-- 탭3 : 모집 마감 -->
    <div id="content3" class="tab-content d-flex justify-content-center">
      <!-- 모집마감 모임 리스트 -->
      <div class="row gx-5 w-100 mx-auto">
        <!-- 반복문 시작 -->
        {% for group in end_groups %}
        <div class="col-12 col-md-6 col-lg-3 group-index-item" style="cursor: pointer;"
          onclick="location.href='{% url 'groups:detail' group.pk %}';">
          <div class="card w-100 mb-5 mx-auto">
            <div class="position-relative card-image" style="height: 250px;">
              <span class="position-absolute p-2 badge rounded-pill text-bg-secondary">모집마감</span>
              <img src="{{ group.image.url }}" class="card-img-top" alt="metting-image" style="height: 100%;">
            </div>
            <div class="card-body">
              <p class="card-title" style="margin-bottom: 10px;overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 1;
              -webkit-box-orient: vertical; font-weight: 600;">{{ group.title }}</p>
              <p class="card-text " style="font-size: 14px; color: var(--gray-dark-color);">장소: {{ group.place }} <br> 인원: {{ group.number }}명 <br> 일시: {{ group.meeting_date|date:"m.d(l) A h:i" }} <br>모집 마감일: {{ group.end_date |date:"m.d A h:i" }}까지</p>
            </div>
          </div>
        </div>
        {% empty %}
        <div class="my-5 d-flex flex-column align-items-center" style="min-height: 250px;">
          <p style="color: var(--gray-dark-color);">모집 마감한 모임이 없습니다</p>
        </div>
        {% endfor %}
        <!-- 반복문 끝 -->
      </div>
    </div>
  </div>
</div>


{% endblock content %}