KDTFinalPJT/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "accounts"

urlpatterns = [
    # path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("signup_done/", views.signup_done, name="signup_done"),
    path("login/", views.login, name="login"),
    path("login_help/", views.login_help, name="login_help"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("password/", views.password, name="password"),
    path("delete/", views.delete, name="delete"),
    path("delete_check/", views.delete_check, name="delete_check"),
    path("<int:user_pk>/detail/", views.detail, name="detail"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KDTFinalPJT/books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path("", views.onboarding, name="onboarding"),
    path("main/", views.main, name="main"),
    path("books/", views.index, name="index"),
    path("books/<int:pk>/detail/", views.detail, name="detail"),
    path("books/<int:book_pk>/like/", views.like, name="like"),
    path("search/", views.search, name="search"),
]

KDTFinalPJT/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("books.urls")),
    path("accounts/", include("accounts.urls")),
    path("notices/", include("notices.urls")),
    path("reviews/", include("reviews.urls")),
    path("groups/", include("groups.urls")),
    path("backend_test/", include("backend_test.urls")),
    path("nav/", views.nav, name="nav"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KDTFinalPJT/groups/urls.py
from django.urls import path
from . import views

app_name = "groups"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/like/", views.like, name="like"),
    path("<int:pk>/group_closed/", views.group_closed, name="group_closed"),
]

KDTFinalPJT/notices/urls.py
from django.urls import path
from . import views


app_name = "notices"
urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
]

KDTFinalPJT/reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:book_pk>/create_txt/", views.create_txt, name="create_txt"),
    path("<int:book_pk>/create_img/", views.create_img, name="create_img"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/update", views.update, name="update"),
    path("<int:pk>/delete", views.delete, name="delete"),
    path("<int:pk>/like/", views.like, name="like"),
    path(
        "<int:review_pk>/comment_create/", views.comment_create, name="comment_create"
    ),
    path(
        "comment_delete/<int:comment_pk>/",
        views.comment_delete,
        name="comment_delete",
    ),
    path("pk_create_txt/", views.pk_create_txt, name="pk_create_txt"),
    path("pk_create_img/", views.pk_create_img, name="pk_create_img"),
]

KDTFinalPJT/config/views.py
from books.models import Book
from django.shortcuts import render


def nav(request):
    books = Book.objects.all()
    context = {
        "books" : books
    }
    return render(request, "nav.html", context)

KDTFinalPJT/config/templates/nav.html
{% load static %}

<!-- Nav -->
<nav class="nav">
  <div class="container nav-box">
    <!-- Nav Logo -->
    <div class="nav__logo">
      <a href="{% url 'books:main' %}">
        <!-- <h4 style="color: var(--main-color); width: 65px; margin: 0; font-family: 'Nanum Myeongjo'">책:오</h3> -->
        <img src="{% static 'img/logo-04.png' %}" alt="logo">
      </a>
    </div>
    <div class="nav-wrap">
      <!-- Nav List -->
      <ul class="nav__list">
        <li class="nav__list__item"><a href="{% url 'books:index' %}">도서목록</a></li>
        <li class="nav__list__item"><a href="{% url 'reviews:index' %}">리뷰목록</a></li>
        <li class="nav__list__item"><a href="{% url 'groups:index' %}">모임목록</a></li>
        <li class="nav__list__item"><a href="{% url 'notices:index' %}">공지사항</a></li>
      </ul>
      <div class="nav-wrap-inner">
        <div class="nav-icon-wrap">
          <!-- Nav Search -->
          <div class="nav__search">
            <form id="search-form" action="{% url 'books:search' %}" method="get">
              <input type="search" name="search" id="d" >
            </form>
            <div class="material-icons">search</div>
          </div>
        </div>
        <!-- Nav User -->
        <div class="nav__user">
          
          {% if request.user.is_authenticated %}
          <a href="{% url 'accounts:detail' request.user.pk %}">
            <img class="nav__user__image" src="{{ request.user.user_image }}" alt="user-profile">
          </a>
          <a href="{% url 'accounts:logout' %}" class="ms-3">
            <!-- fa-door-open / fa-person-walking-arrow-right 
              fa-right-from-bracket / fa-arrow-right-from-bracket -->
            <i class="fa-solid fa-arrow-right-from-bracket fa-xl" style="color: var(--main-color);"></i>
          </a>
          {% else %}
          <a href="{% url 'accounts:login' %}">
            <button class="nav__user__btn btn btn--main">로그인</button>
          </a>
          <a href="{% url 'accounts:signup' %}">
            <button class="nav__user__btn btn btn--main--reverse">회원가입</button>
          </a>
          {% endif %}
            
        </div>
      </div>
    </div>
    <a href="#" class="nav-toogle-btn">
      <i class="fa-solid fa-bars-staggered fa-xl"></i>
    </a>
  </div>
</nav>