KDTFinalPJT/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "accounts"

urlpatterns = [
    # path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("signup_done/", views.signup_done, name="signup_done"),
    path("login/", views.login, name="login"),
    path("login_help/", views.login_help, name="login_help"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("password/", views.password, name="password"),
    path("delete/", views.delete, name="delete"),
    path("delete_check/", views.delete_check, name="delete_check"),
    path("<int:user_pk>/detail/", views.detail, name="detail"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KDTFinalPJT/books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path("", views.onboarding, name="onboarding"),
    path("main/", views.main, name="main"),
    path("books/", views.index, name="index"),
    path("books/<int:pk>/detail/", views.detail, name="detail"),
    path("books/<int:book_pk>/like/", views.like, name="like"),
    path("search/", views.search, name="search"),
]

KDTFinalPJT/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("books.urls")),
    path("accounts/", include("accounts.urls")),
    path("notices/", include("notices.urls")),
    path("reviews/", include("reviews.urls")),
    path("groups/", include("groups.urls")),
    path("backend_test/", include("backend_test.urls")),
    path("nav/", views.nav, name="nav"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KDTFinalPJT/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class User(AbstractUser):
    nickname = models.CharField(max_length=20)
    interest = models.CharField(null=False, default="", max_length=20)
    profile_image = ProcessedImageField(
        upload_to="media/",
        blank=True,
        processors=[ResizeToFill(200, 200)],
        format="JPEG",
        options={"quality": 70},
    )
    age = models.PositiveIntegerField(default=0)
    status_message = models.TextField()
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )

    def user_image(self):
        if self.profile_image and hasattr(self.profile_image, "url"):
            return self.profile_image.url
        else:
            return "/static/image/no_profile.png"

KDTFinalPJT/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.auth import get_user_model


class CustomCreationUserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ["username", "interest"]
        labels = {"username": "이름", "interest": "관심분야"}


class CustonChangeUserForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = [
            "nickname",
            "email",
            "age",
            "profile_image",
            "status_message",
            "interest",
        ]
        labels = {
            "nickname": "닉네임",
            "email": "이메일",
            "age": "나이",
            "profile_image": "프로필 사진",
            "status_message": "상태 메세지",
            "interest": "관심분야",
        }

KDTFinalPJT/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from .forms import CustomCreationUserForm, CustonChangeUserForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout, authenticate
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from datetime import datetime
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from books.models import Book

# Create your views here.
# def index(request):
#     users = get_user_model().objects.all()
#     context = {"users": users}
#     return render(request, "accounts/index.html", context)


# 회원가입
def signup(request):
    if request.method == "POST":
        form = CustomCreationUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            auth_login(request, user)
            return redirect("accounts:signup_done")
    else:
        form = CustomCreationUserForm()

    context = {"form": form}

    return render(request, "accounts/signup.html", context)


# 회원가입 완료
def signup_done(request):
    return render(request, "accounts/signup_done.html")


# 로그인
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("books:main")
    else:
        form = AuthenticationForm()
    context = {"form": form}

    return render(request, "accounts/login.html", context)


# 로그인 도움말
def login_help(request):
    return render(request, "accounts/login_help.html")


# 로그아웃
def logout(request):
    auth_logout(request)
    return redirect("books:main")


# 회원 정보 수정
@login_required
def update(request):
    user = get_user_model().objects.get(pk=request.user.pk)
    if request.method == "POST":
        form = CustonChangeUserForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", user.pk)

    else:
        form = CustonChangeUserForm(instance=request.user)

    context = {"form": form, "user": user}

    return render(request, "accounts/update.html", context)


# 회원 비밀번호 변경
@login_required
def password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)  # 로그인 유지
            return redirect("accounts:login")

    else:
        form = PasswordChangeForm(request.user)

    context = {
        "form": form,
    }

    return render(request, "accounts/password.html", context)


# 회원 탈퇴
@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("books:main")


# 회원 탈퇴 체크
def delete_check(request):
    user = get_user_model().objects.get(pk=request.user.pk)
    today = datetime.date(datetime.now())
    date_joined = datetime.date(user.date_joined)
    diff = (today - date_joined).days + 1
    reviews = user.book_review_set.count
    user_groups = user.group_set.count
    context = {
        "user": user,
        "diff": diff,
        "reviews": reviews,
        "user_groups": user_groups,
    }
    return render(request, "accounts/delete.html", context)


# 회원 정보
def detail(request, user_pk):
    user = get_user_model().objects.get(pk=user_pk)
    book_likes = user.books.all()
    user_reviews = user.book_review_set.order_by("-pk")
    user_like_reviews = user.like_review.order_by("-pk")
    user_groups = user.group_set.order_by("-pk")
    user_like_groups = user.like_group.order_by("-pk")
    context = {
        "user": user,
        "book_likes": book_likes,
        "user_reviews": user_reviews,
        "user_like_reviews": user_like_reviews,
        "user_groups": user_groups,
        "user_like_groups": user_like_groups,
    }

    return render(request, "accounts/detail.html", context)


# 팔로우
@login_required
def follow(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)
    if request.user != get_user_model().objects.get(pk=user_pk):
        if user.followers.filter(pk=request.user.pk).exists():
            user.followers.remove(request.user)
            is_followed = False
        else:
            user.followers.add(request.user)
            is_followed = True
        context = {
            "is_followed": is_followed,
            "followers_count": user.followers.count(),
            "followings_count": user.followings.count(),
        }
        return JsonResponse(context)

KDTFinalPJT/accounts/templates/accounts/delete.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
{% include 'nav.html' %}

<div class="container delete">
  <!-- delete box -->
  <div class="delete-box p-5">
    <h4 class="text-center mb-4">회원탈퇴</h4>
    <!-- user record -->
    <div class="my-5 mx-auto w-50">
      <p class="gray-text text-center fw-bold">{{ user.username }}님의 활동</p>
      <dl class="row">
        <dt class="col-sm-8 gray-text">책:오와 함께한 시간</dt>
        <dd class="col-sm-4 text-center fw-bold">{{ diff }}일</dd>
        <dt class="col-sm-8 gray-text">기록한 리뷰</dt>
        <dd class="col-sm-4 text-center fw-bold">{{ reviews }}개</dd>
        <dt class="col-sm-8 gray-text">개최한 모임</dt>
        <dd class="col-sm-4 text-center fw-bold">{{ user_groups }}개</dd>
      </dl>
    </div>
    <p class="text-center my-5">탈퇴하면 여러분의 책:크 기록이 없어져요..<i class="fa-regular fa-face-sad-tear"></i></p>
    <!-- delete form -->
    <form action="{% url 'accounts:delete' %}">
      {% csrf_token %}
      <!-- checkbox -->
      <div class="mx-2 mb-3">
        <input type="checkbox" name="agree" onClick="agreeCheck(this.form)">
        <label class="gray-text" for="agree">안내사항을 확인하고 탈퇴에 동의합니다.</label>
      </div>
      <!-- delete btn -->
      <input class="btn btn--main--reverse w-100 mb-3" disabled="disabled" type="submit" name="checkButton" value="탈퇴하기">
    </form>
  </div>
</div>

<script>
  // 삭제 폼 동의 체크여부 확인
  function agreeCheck(frm) {
     if (frm.checkButton.disabled==true)
      frm.checkButton.disabled=false
     else
      frm.checkButton.disabled=true
  }
</script>

{% endblock content %}

KDTFinalPJT/accounts/templates/accounts/index.html
{% extends 'base.html' %}


{% block content %}
{% if request.user.is_authenticated %}
  <p>{{ request.user }}님</p>
  <div>회원정보
    <div>
      <!-- 전체 유저 정보 -->
      {% for user in users  %}
      <a href="{% url 'accounts:detail' user.pk %}">{{ user }}</a> 
      {% endfor %}
      <!-- 로그아웃 -->
      <form action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="logout">
      </form>
      <!-- 회원탈퇴 -->
      <a href="{% url 'accounts:delete_check' %}">탈퇴하기</a> 
    </div>
  </div>

{% else %}
  <div>
    <a href="{% url 'accounts:signup' %}">회원가입</a>
  </div> 
  <div>
    <a href="{% url 'accounts:login' %}">로그인</a>
  </div>
{% endif %}

 

{% endblock content %}
  

KDTFinalPJT/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
{% include 'nav.html' %}

<div class="container login">
    <form class="login-form p-5" action="" method="POST">
        <h4 class="text-center mb-4">로그인</h4>
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label" for="id_username">사용자 이름</label>
            <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" class="form-control" placeholder="사용자 이름" required="" id="id_username">
        </div>
        <div class="mb-3">
            <label class="form-label" for="id_password">비밀번호</label>
            <input type="password" name="password" autocomplete="current-password" class="form-control" placeholder="비밀번호" required="" id="id_password">
        </div>
        <input class="btn btn--main--reverse w-100 mb-3" type="submit" value="로그인하기">
        <div class="d-flex justify-content-center">
            <a class="login-help" href="{% url 'accounts:login_help' %}">로그인에 어려움이 있으신가요?</a>
        </div>
    </form>
</div>

{% endblock content %}
  

KDTFinalPJT/accounts/templates/accounts/login_help.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
{% include 'nav.html' %}

<div class="container login">
  <!-- help box -->
  <div class="login-help-box p-5">
    <h4 class="text-center mb-4">로그인에 어려움이 있나요?</h4>
    <!-- help content -->
    <div class="my-5">
        <p class="text-center">로그인에 어려움이 있다면 아래 이메일로 문의해주세요.</p>
        <p class="text-center">편리한 이용을 위해 계속해서 발전하는 책:오가 되겠습니다 :)</p>
    </div>
    <p class="text-center">👇 문의하기 클릭 👇</p>
    <!-- sumbit -->
    <a class="btn btn--main--reverse w-100" href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;to=ericaforcoding@gmail.com" target="_blank">ericaforcoding@gmail.com<a>
  </div>
</div>

{% endblock content %}

KDTFinalPJT/accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
{% include 'nav.html' %}

<div class="container password">
  <!-- 비밀번호 변경 폼-->
  <form class="password-form p-5" action="" method='POST'>
    <h4 class="text-center mb-4">비밀번호 변경</h4>
    {% csrf_token %}
    {% bootstrap_form form %}
    <!-- submit -->
    <input class="btn btn--main--reverse w-100 mb-3" type="submit" value="Register">
  </form>
</div>

{% endblock content %}

KDTFinalPJT/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
{% include 'nav.html' %}

<div class="container signup">
  <!-- signup form -->
  <form class="signup-form p-5" action="" method="POST">
    <h4 class="text-center mb-4">회원가입</h4>
    {% csrf_token %}
    <!-- input -->
    <div class="mb-3">
      <label class="form-label" for="id_username">이름</label>
      <input type="text" name="username" maxlength="150" autofocus="" class="form-control" placeholder="이름" required="" id="id_username">
    </div>
    <div class="mb-3">
      <label class="form-label" for="id_password1">비밀번호</label>
      <input type="password" name="password1" autocomplete="new-password" class="form-control" placeholder="비밀번호" required="" id="id_password1">
    </div>
    <div class="mb-3">
      <label class="form-label" for="id_password2">비밀번호 확인</label>
      <input type="password" name="password2" autocomplete="new-password" class="form-control" placeholder="비밀번호 확인" required="" id="id_password2">
    </div>
    <fieldset class="mb-3">
      <label class="form-label" for="id_interest">관심분야</label>
      <div class="interest">
        <input class="radioInp" type="radio" id="총류" name="interest" value="총류" checked><label for="총류">총류</label>
        <input class="radioInp" type="radio" id="철학" name="interest" value="철학"><label for="철학">철학</label>
        <input class="radioInp" type="radio" id="종교" name="interest" value="종교"><label for="종교">종교</label>
        <input class="radioInp" type="radio" id="사회과학" name="interest" value="사회과학"><label for="사회과학">사회과학</label>
        <input class="radioInp" type="radio" id="자연과학" name="interest" value="자연과학"><label for="자연과학">자연과학</label>
        <input class="radioInp" type="radio" id="기술과학" name="interest" value="기술과학"><label for="기술과학">기술과학</label>
        <input class="radioInp" type="radio" id="예술" name="interest" value="예술"><label for="예술">예술</label>
        <input class="radioInp" type="radio" id="언어" name="interest" value="언어"><label for="언어">언어</label>
        <input class="radioInp" type="radio" id="문학" name="interest" value="문학"><label for="문학">문학</label>
        <input class="radioInp" type="radio" id="역사" name="interest" value="역사"><label for="역사">역사</label>
      </div>
    </fieldset>
    <!-- sumbit -->
    <input class="btn btn--main--reverse w-100 mb-3" type="submit" value="등록하기">
  </form>
</div>

{% endblock content %}

KDTFinalPJT/accounts/templates/accounts/signup_done.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
{% include 'nav.html' %}

<div class="container signup">
  <!-- signup form -->
  <div class="signup-done p-5" action="" method="POST">
    <h4 class="text-center mb-4">책:오에 오신 것을 환영합니다!</h4>
    <!-- welcome icon -->
    <div class="w-100 d-flex justify-content-center my-3">
      <script src="https://cdn.lordicon.com/fudrjiwc.js"></script>
      <lord-icon
          src="https://cdn.lordicon.com/lupuorrc.json"
          trigger="loop"
          delay="2000"
          colors="primary:#121331,secondary:#92b4ec"
          stroke="60"
          style="width:250px;height:250px">
      </lord-icon>
    </div>
    <!-- sumbit -->
    <a class="btn btn--main--reverse w-100" href="{% url 'books:main' %}">책:오 구경하러 가기<a>
  </div>
</div>

{% endblock content %}

KDTFinalPJT/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
{% include 'nav.html' %}

<div class="container update">
    <!-- update form -->
    <form class="update-form p-5" name="update_form" onsubmit="return ageCheck();" action="" method="POST" enctype="multipart/form-data">
        <h4 class="text-center mb-4">회원정보 수정</h4>
        {% csrf_token %}
        <!-- input -->
        <div class="row">
            <div class="col-12 col-md-4">
                <div class="mb-3">
                    <label class="form-label" for="id_profile_image">프로필 사진</label>
                    <div class="mx-auto mb-2" style="width: 180px; height: 180px">
                        <img class="w-100 h-100 rounded-circle border" style="object-fit: cover;" id="profile-image" src="/static/image/no_profile.png">
                    </div>
                    <input type="file" name="profile_image" accept="image/*" class="form-control" id="id_profile_image">
                </div>
            </div>
            <div class="col-12 col-md-8">
                <div class="mb-4">
                    <label class="form-label" for="id_nickname">닉네임</label>
                    <input type="text" name="nickname" maxlength="20" class="form-control" placeholder="닉네임" required="" id="id_nickname" value="{{ user.nickname }}">
                </div>
                <div class="mb-4">
                    <label class="form-label" for="id_email">이메일</label>
                    <input type="email" name="email" maxlength="254" class="form-control" placeholder="이메일" id="id_email" value="{{ user.email }}">
                </div>
                <div class="mb-4">
                    <label class="form-label" for="id_age">나이</label>
                    {% if user.age == 0 %}
                    <input type="number" name="age" class="form-control" placeholder="나이" required="" id="id_age" value="">
                    {% else %}
                    <input type="number" name="age" class="form-control" placeholder="나이" required="" id="id_age" value="{{ user.age }}">
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="mb-4">
            <label class="form-label" for="id_status_message">상태 메세지</label>
            <textarea name="status_message" cols="40" rows="3" class="form-control" placeholder="상태 메세지" required="" id="id_status_message">{{ user.status_message }}</textarea>
        </div>
        <div class="mb-4 d-none">
            <label class="form-label" for="id_interest">관심분야</label>
            <input type="text" name="interest" value="{{ user.interest }}" maxlength="20" class="form-control" placeholder="관심분야" required="" id="id_interest">
        </div>
        <fieldset class="mb-4">
            <label class="form-label" for="id_interest">관심분야</label>
            <div class="interest">
                <input class="radioInp" type="radio" id="총류" name="interest" value="총류"><label for="총류">총류</label>
                <input class="radioInp" type="radio" id="철학" name="interest" value="철학"><label for="철학">철학</label>
                <input class="radioInp" type="radio" id="종교" name="interest" value="종교"><label for="종교">종교</label>
                <input class="radioInp" type="radio" id="사회과학" name="interest" value="사회과학"><label for="사회과학">사회과학</label>
                <input class="radioInp" type="radio" id="자연과학" name="interest" value="자연과학"><label for="자연과학">자연과학</label>
                <input class="radioInp" type="radio" id="기술과학" name="interest" value="기술과학"><label for="기술과학">기술과학</label>
                <input class="radioInp" type="radio" id="예술" name="interest" value="예술"><label for="예술">예술</label>
                <input class="radioInp" type="radio" id="언어" name="interest" value="언어"><label for="언어">언어</label>
                <input class="radioInp" type="radio" id="문학" name="interest" value="문학"><label for="문학">문학</label>
                <input class="radioInp" type="radio" id="역사" name="interest" value="역사"><label for="역사">역사</label>
            </div>
        </fieldset>
        <!-- password change -->
        <div class="mb-4">
            <div class="form-control-static" disabled="" id="id_password">
                <strong>비밀번호가 설정되지 않습니다.</strong>
            </div>
            <div class="form-text">원본 비밀번호는 저장되지 않으므로, 해당 사용자의 비밀번호를 확인할 수 없습니다. 다만 이 <a style="color: var(--main-color)" href="../password/">폼</a>을 사용하여 비밀번호를 변경할 수 있습니다.</div>
        </div>
        <!-- sumbit -->
        <input class="btn btn--main--reverse w-100 mb-3" type="submit" value="등록하기">
    </form>
</div>

<!-- Sweet alert -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script>
    function readImage(input) {
        // 인풋 태그에 파일이 있는 경우
        if(input.files && input.files[0]) {
            // 이미지 파일인지 검사 (생략)
            // FileReader 인스턴스 생성
            const reader = new FileReader()
            // 이미지가 로드가 된 경우
            reader.onload = e => {
                const previewImage = document.getElementById("profile-image")
                previewImage.src = e.target.result
            }
            // reader가 이미지 읽도록 하기
            reader.readAsDataURL(input.files[0])
        }
    }
    // input file에 change 이벤트 부여
    const inputImage = document.getElementById("id_profile_image")
    inputImage.addEventListener("change", e => {
        readImage(e.target)
    })

    // user interest 관심분야 값 불러오기
    var interest = document.querySelector("#id_interest").value
    console.log(interest)
    
    // change form의 interest radio 버튼 그룹에서
    var radioGroup = document.getElementsByName("interest")
    // 반복문 돌려서 관심분야와 같은 값의 버튼 체크
    for (var i = 0; i < radioGroup.length; i++) {
        if (radioGroup[i].value === interest) {
            console.log(radioGroup[i])
            radioGroup[i].checked = true
        }
    }

    // 나이가 양수 이상인지 확인
    function ageCheck() {
        // 음수이면
        if(update_form.age.value <= 0) {
            // Sweet alert
            Swal.fire({
                icon: 'question',
                iconHtml: '!',
                title: update_form.age.value+'살이요...?',
                text: '본인 나이를 작성해주세요!',
                confirmButtonColor: '#92B4EC',
            })
            update_form.age.focus();
            // false : submit X
            return false;
        }
        else {
            // true : submit reader.onload
            return true;
        }
    }
</script>

{% endblock content %}