KDTFinalPJT/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "accounts"

urlpatterns = [
    # path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("signup_done/", views.signup_done, name="signup_done"),
    path("login/", views.login, name="login"),
    path("login_help/", views.login_help, name="login_help"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("password/", views.password, name="password"),
    path("delete/", views.delete, name="delete"),
    path("delete_check/", views.delete_check, name="delete_check"),
    path("<int:user_pk>/detail/", views.detail, name="detail"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KDTFinalPJT/books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path("", views.onboarding, name="onboarding"),
    path("main/", views.main, name="main"),
    path("books/", views.index, name="index"),
    path("books/<int:pk>/detail/", views.detail, name="detail"),
    path("books/<int:book_pk>/like/", views.like, name="like"),
    path("search/", views.search, name="search"),
]

KDTFinalPJT/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("books.urls")),
    path("accounts/", include("accounts.urls")),
    path("notices/", include("notices.urls")),
    path("reviews/", include("reviews.urls")),
    path("groups/", include("groups.urls")),
    path("backend_test/", include("backend_test.urls")),
    path("nav/", views.nav, name="nav"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KDTFinalPJT/groups/urls.py
from django.urls import path
from . import views

app_name = "groups"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/like/", views.like, name="like"),
    path("<int:pk>/group_closed/", views.group_closed, name="group_closed"),
]

KDTFinalPJT/reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:book_pk>/create_txt/", views.create_txt, name="create_txt"),
    path("<int:book_pk>/create_img/", views.create_img, name="create_img"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/update", views.update, name="update"),
    path("<int:pk>/delete", views.delete, name="delete"),
    path("<int:pk>/like/", views.like, name="like"),
    path(
        "<int:review_pk>/comment_create/", views.comment_create, name="comment_create"
    ),
    path(
        "comment_delete/<int:comment_pk>/",
        views.comment_delete,
        name="comment_delete",
    ),
    path("pk_create_txt/", views.pk_create_txt, name="pk_create_txt"),
    path("pk_create_img/", views.pk_create_img, name="pk_create_img"),
]

KDTFinalPJT/books/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings


class Book(models.Model):
    bookname = models.CharField(max_length=1000)
    authors = models.CharField(max_length=1000)
    publisher = models.CharField(max_length=1000)
    publication_year = models.CharField(max_length=1000)
    class_nm = models.CharField(max_length=2000)
    bookcover = models.CharField(max_length=1000)
    description = models.CharField(max_length=1000)
    like_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="books")

KDTFinalPJT/reviews/models.py
from django.db import models
from django.contrib.auth import get_user_model
from books.models import Book
from taggit.managers import TaggableManager
from django.utils import timezone
from datetime import datetime, timedelta


class Book_Review(models.Model):
    content = models.TextField(blank=True)
    image = models.ImageField(blank=True)
    color = models.CharField(max_length=7, default="#FFFFFF")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    like_user = models.ManyToManyField(get_user_model(), related_name="like_review")
    bookId = models.ForeignKey(Book, on_delete=models.CASCADE)
    tags = TaggableManager(blank=True)

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return "방금 전"
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + "분 전"
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + "시간 전"
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + "일 전"
        else:
            return False


class Book_Review_Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    book_review = models.ForeignKey(Book_Review, on_delete=models.CASCADE)

KDTFinalPJT/books/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Book
from django.http import HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.db.models import Count
from urllib import parse
from django.db.models import Q
from accounts.models import User
from books.models import Book
from reviews.models import Book_Review
from groups.models import Group
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag


def onboarding(request):
    books = Book.objects.all().annotate(hot=Count("like_user")).order_by("-hot")
    reviews = Book_Review.objects.annotate(hot=Count("like_user")).order_by("-hot")

    return render(
        request,
        "books/onboarding.html",
        {
            "books": books,
            "reviews": reviews,
        },
    )


# 메인 페이지
def main(request):
    books = Book.objects.all().annotate(hot=Count("like_user")).order_by("-hot")
    reviews = Book_Review.objects.annotate(hot=Count("like_user")).order_by("-hot")
    groups = Group.objects.filter(closed=0).order_by("-pk")

    return render(
        request,
        "books/main.html",
        {
            "books": books[:4],
            "reviews": reviews[:3],
            "book_reviews_carousel": reviews[:10],
            "groups": groups[:3],
        },
    )


# 책 리스트 페이지
def index(request):
    if request.GET.get("page"):
        books = Book.objects.all()
        page1 = request.GET.get("page", 1)
        totalnum = len(books)
        books_page = Paginator(books, 20)
        totalpagenum = books_page.num_pages
        try:
            book_list = books_page.page(page1)
        except PageNotAnInteger:
            book_list = books_page.page(1)
        except EmptyPage:
            book_list = books_page.page(books_page.num_pages)

    else:
        books = Book.objects.all()
        page1 = request.GET.get("page", 1)
        totalnum = len(books)
        books_page = Paginator(books, 20)
        totalpagenum = books_page.num_pages
        try:
            book_list = books_page.page(page1)
        except PageNotAnInteger:
            book_list = books_page.page(1)
        except EmptyPage:
            book_list = books_page.page(books_page.num_pages)

    count = Book.objects.all().count()

    return render(
        request,
        "books/index.html",
        {
            "books": books,
            "book_list": book_list,
            "totalnum": totalnum,
            "totalpagenum": totalpagenum,
            "count": count,
        },
    )


# 책 디테일 페이지(댓글추가전)
def detail(request, pk):
    book = Book.objects.get(pk=pk)
    book_url = parse.quote(book.bookname)
    book_reviews = book.book_review_set.order_by("-pk")
    context = {
        "book": book,
        "book_url": book_url,
        "book_reviews": book_reviews,
        "book_reviews_writer": book_reviews[:8],
        "book_reviews_carousel": book_reviews[:10],
    }
    return render(request, "books/book_detail.html", context)


def like(request, book_pk):
    book = get_object_or_404(Book, pk=book_pk)
    if request.user in book.like_user.all():
        book.like_user.remove(request.user)
        is_liked = False
    else:
        book.like_user.add(request.user)
        is_liked = True
    context = {
        "isLiked": is_liked,
        "like_count": book.like_user.count(),
    }

    return JsonResponse(context)


# navbar search 기능
def search(request):
    book = None
    user = None
    query = None
    reviews = None
    authors = None
    tags = None
    if "search" in request.GET:
        query = request.GET.get("search")
        book = Book.objects.order_by("-pk").filter(bookname__contains=query)
        authors = Book.objects.order_by("-pk").filter(authors__contains=query)
        user = User.objects.order_by("-pk").filter(nickname__contains=query)
        reviews = Book_Review.objects.filter(content__contains=query)
        tags = Tag.objects.filter(name__contains=query)
        tags_review = Book_Review.objects.filter(tags__name__contains=query)

    context = {
        "query": query,
        "books": book,
        "user": user,
        "reviews": reviews,
        "authors": authors,
        "tags": tags,
        "tags_review": tags_review,
    }

    return render(request, "books/search.html", context)

KDTFinalPJT/books/templates/books/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

  <h1>create</h1>
  <div class="container">
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form book_review_form %}
      <button type="submit">제출</button>

    </form>
  </div>

{% endblock content %}

KDTFinalPJT/books/templates/books/main.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
{% include 'nav.html' %}

<!-- Main-swiper -->
<section class="main-swiper">
  <div class="container">
    <!-- Swiper -->
    <div class="swiper mainSwiper">
      <div class="swiper-wrapper">
        <div class="swiper-slide">
          <img src="https://cdn.pixabay.com/photo/2022/11/02/22/46/festive-season-7566217_1280.jpg" alt="main-swiper-image">
        </div>
        <div class="swiper-slide">
          <img src="https://cdn.pixabay.com/photo/2014/01/29/04/37/book-254048_1280.jpg" alt="main-swiper-image">
        </div>
        <div class="swiper-slide">
          <img src="https://cdn.pixabay.com/photo/2018/04/06/23/22/notebook-3297317_1280.jpg" alt="main-swiper-image">
        </div>
        <div class="swiper-slide">
          <img src="https://cdn.pixabay.com/photo/2022/08/14/11/29/friend-7385640_1280.jpg" alt="main-swiper-image">
        </div>
      </div>
      <div class="swiper-pagination"></div>
    </div>
  </div>
</section>


<!-- Main-book -->
<section class="main-book">
  <div class="container">
    <!-- Main-book-top -->
    <div class="mb__top">
      <h3 class="mb__title">인기 도서 목록</h3>
      <a href="{% url 'books:index' %}">
        <span class="me-1">더보기</span><i class="fa-solid fa-arrow-right"></i>
      </a>
    </div>
    <!-- Main-book-list -->
    <div class="mb__list">
      {% for book in books %}
      <!-- Main-book-item -->
      <a href="{% url 'books:detail' book.pk %}">
        <div class="mb__list__item">
          <div class="mb__list__image">
            <div class="image-cover">
              <p class="m-0"><i class="fa-solid fa-pencil"></i> {{ book.book_review_set.count }}</p>
              <p><i class="fa-solid fa-heart"></i> {{ book.like_user.count }}</p>
            </div>
            <img src="{{ book.bookcover }}" alt="bookcover">
          </div>
          <div class="mb__list__item__text">
            <p class="fw-bold">{{ book.bookname }}</p>
            <p>{{ book.authors }}</p>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
</section>


<!-- Main-review -->
<section class="main-review">
  <div class="container">
    <!-- Main-review-top -->
    <div class="mr__top">
      <h3 class="mr__title">인기 리뷰 목록</h3>
      <a href="{% url 'reviews:index' %}">
        <span class="me-1">더보기</span><i class="fa-solid fa-arrow-right"></i>
      </a>
    </div>
    <!-- Main-review-list -->
    <div class="mr__list">
      {% for review in reviews %}
      <!-- Main-review-item -->
      <div class="mr__list__item">
        <div class="mr__item__content p-0" style="cursor: pointer; background-color: {{ review.color }};"
          onclick="location.href='{% url 'reviews:detail' review.pk %}';">
          {% if review.content != "" %}
          <div class="review__item__content__quote">
            <div class="up-quote">
              <i class="fa-solid fa-quote-left fa-lg"></i>
            </div>
            <p class="text-center m-0">{{ review.content }}</p>
            <div class="down-quote">
              <i class="fa-solid fa-quote-right fa-lg"></i>
            </div>
          </div>
          {% else %}
          <img class="bookReviewCardImage border" src="{{ review.image.url }}" alt="">
          {% endif %}
        </div>
        <div class="mr__item__writer">
          <a href="{% url 'accounts:detail' review.user.pk %}" class="d-flex align-items-center">
            <div class="mr__item__writer-image">
              <img src="{{ review.user.user_image }}" alt="review-writer-image">
            </div>
            <div class="mr__item__writer-name">
              <p>{{ review.user.username }}</p>
            </div>
          </a>
          {% if request.user.is_authenticated %}
          <div class="mr__item-like">
            <!-- review-item-button -->
            <div class="review__item__btn">
              <div id="like-count-{{ review.pk }}" class="m-0 me-2 fw-bold" style="color: var(--main-color);">
                {{ review.like_user.count }}
              </div>
              <!-- review-like-form -->
              <form class="like-forms" data-review-id="{{ review.pk }}">
                {% csrf_token %}
                {% if user in review.like_user.all %}
                <button id="like-{{ review.pk }}" type="submit">
                  <i id="heart-{{ review.pk }}" class="fa-solid fa-heart fa-lg"></i>
                </button>
                {% else %}
                <button id="like-{{ review.pk }}" type="submit">
                  <i id="heart-{{ review.pk }}" class="fa-regular fa-heart fa-lg"></i>
                </button>
                {% endif %}
              </form>
              <!--공유하기-->
              <i type="button" class="fa-solid fa-share-nodes fa-lg" data-bs-toggle="modal"
                data-bs-target="#exampleModal"></i>
              <!-- Modal -->
              <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header justify-content-center">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">공유하기</h1>
                    </div>
                    <div class="modal-body">
                      <div class="d-flex justify-content-center">
                        <a href="javascript:sendLinkFacebook()"><i class="bi bi-facebook mx-3"
                            style="font-size: 52px;"></i></a>
                        <a href="javascript:sendLinkTwitter()"><i class="bi bi-twitter mx-3"
                            style="font-size: 52px;"></i></a>
                        <script>
                          function sendLinkFacebook() {
                            var facebook_share_url = "https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}";
                            window.open(facebook_share_url,
                              'Share on Facebook',
                              'scrollbars=no, width=500, height=500');
                          }

                          function sendLinkTwitter() {
                            var twitter_share_text = "{{ post.title }}";
                            var twitter_share_url = "{{ request.build_absolute_uri }}";
                            window.open("https://twitter.com/share?text=" + twitter_share_text + "&url=" + twitter_share_url,
                              'Share on Twitter',
                              'scrollbars=no, width=500, height=500');
                          }
                        </script>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% else %}
          <a href="{% url 'accounts:login' %}">
            <span style="color: var(--dark-color); font-size: 14px;">로그인 이후 사용이 가능합니다.</span>
          </a>
          {% endif %}

        </div>
      </div>
      {% empty %}
      <div class="my-5 d-flex flex-column align-items-center">
        <p style="color: var(--gray-color);">책:오의 첫 리뷰 주인공이 되어주세요!</p>
        <button class="btn btn--main mt-3" data-bs-toggle="modal" data-bs-target="#review-guide">리뷰 작성</button>
      </div>
      {% endfor %}
    </div>
  </div>
</section>


<!-- Main-metting -->
<section class="main-metting">
  <div class="container">
    <!-- Main-metting-top -->
    <div class="mm__top">
      <h3 class="mm__title">진행중인 모임 목록</h3>
      <a href="{% url 'groups:index' %}">
        <span class="me-1">더보기</span><i class="fa-solid fa-arrow-right"></i>
      </a>
    </div>
    <!-- Main-metting-list -->
    <div class="mm__list">
      <!-- main-metting-item -->
      {% for group in groups %}
      <div class="mm__list__item">
        <div class="card">
          <div class="card-image">
            <a href="{% url 'groups:detail' group.pk %}">
              <img src="{{ group.image.url }}" class="card-img-top" alt="metting-image">
            </a>
          </div>
          <div class="card-body">
            <h6 class="card-title ellipsis-01" style="margin-bottom: 20px;">{{ group.title }}</h6>
            <p class="card-text" style="font-size: 14px;">
              <span class="ellipsis-01" style="font-size: 14px;">소개: {{ group.introduce }}<br /></span>
              <span class="ellipsis-01" style="font-size: 14px;">장소: {{ group.place }}<br /></span>
              인원: {{ group.number }}명<br />
              일시: {{ group.meeting_date|date:"m.d(l) A h:i" }}<br />
            </p>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="my-5 d-flex flex-column align-items-center">
        <p style="color: var(--gray-color);">책:오의 첫 모임 주인공이 되어주세요!</p>
        <a href="{% url 'groups:create' %}">
          <button class="btn btn--main mt-3">모임 생성</button>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<!-- Write-global-button -->
<div class="write-gb">
  <button type="button" data-bs-toggle="modal" data-bs-target="#review-guide-main">
    <lord-icon src="https://cdn.lordicon.com/puvaffet.json" trigger="hover" colors="primary:#6c757d,secondary:#92B4EC">
    </lord-icon>
  </button>
</div>
<!-- reivew-guide-modal -->
<div class="modal fade" id="review-guide-main" tabindex="-1" aria-labelledby="review-guide" aria-hidden="true">
  <!-- modal-dialog -->
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- modal-body -->
      <div class="modal-body">
        <p class="record-text">기록할 유형을 선택해주세요 ✍️</p>
        <!-- Record-wrap -->
        <div class="record-wrap">
          <!-- record-wording -->
          <a href="{% url 'reviews:pk_create_txt' %}">
            <div class="record-wording">
              <lord-icon src="https://cdn.lordicon.com/nocovwne.json" trigger="hover"
                colors="primary:#6c757d,secondary:#6c757d" stroke="30" style="width:250px;height:250px">
              </lord-icon>
              <h5 class="word">문장 기록</h5>
            </div>
          </a>
          <!-- record-photo -->
          <a href="{% url 'reviews:pk_create_img' %}">
            <div class="record-photo">
              <lord-icon src="https://cdn.lordicon.com/vixtkkbk.json" trigger="hover"
                colors="primary:#6c757d,secondary:#6c757d" stroke="30" style="width:250px;height:250px">
              </lord-icon>
              <h5>사진 기록</h5>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}



{% block js %}

<!-- CDN axios -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<!-- review-create-modal -->
<script>
  // reivew-create-modal
  const wording = document.querySelector(".record-wording");
  const wordingIcon = wording.querySelector('lord-icon');
  const wordingHtag = wording.querySelector('h5');
  const photo = document.querySelector('.record-photo');
  const photoIcon = photo.querySelector('lord-icon');
  const photoHtag = photo.querySelector('h5');

  wording.addEventListener('mouseenter', () => {
      wordingIcon.setAttribute('colors', 'primary:#92B4EC,secondary:#92B4EC');
      wordingHtag.style.color = '#92B4EC';
  });
  wording.addEventListener('mouseleave', () => {
      wordingIcon.setAttribute('colors', 'primary:#6c757d,secondary:#6c757d');
      wordingHtag.style.color = '#6c757d';
  });
  photo.addEventListener('mouseenter', () => {
      photoIcon.setAttribute('colors', 'primary:#92B4EC,secondary:#92B4EC');
      photoHtag.style.color = '#92B4EC';
  });
  photo.addEventListener('mouseleave', () => {
      photoIcon.setAttribute('colors', 'primary:#6c757d,secondary:#6c757d');
      photoHtag.style.color = '#6c757d';
  });
</script>

<!-- Likes -->
<script>
  const forms = document.querySelectorAll('.like-forms')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

  forms.forEach((form) => {
    form.addEventListener('submit', function (evnet) {
      event.preventDefault();
      const reviewId = event.target.dataset.reviewId
      // request axios
      axios({
        method: 'post',
        url: `/reviews/${reviewId}/like/`,
        headers: { 'X-CSRFToken': csrftoken }, // csrf token
      })
        // response views
        .then((response) => {
          const isLiked = response.data.is_liked
          const heartBtn = document.querySelector(`#heart-${reviewId}`)
          const likeCountTag = document.querySelector(`#like-count-${reviewId}`)
          const likeCount = response.data.like_count
          likeCountTag.innerText = likeCount
          if (isLiked === true) {
            heartBtn
              .classList
              .remove('fa-regular')
            heartBtn
              .classList
              .add('fa-solid')
            heartBtn.style.color = 'var(--main-color)';
          } else {
            heartBtn
              .classList
              .remove('fa-solid')
            heartBtn
              .classList
              .add('fa-regular')
            heartBtn.style.color = 'var(--main-color)';
          }
        })
        .catch((error) => {
          console.log(error.response)
        })
    })
  })
</script>

<script src="{% static 'js/write-btn.js' %}"></script>

{% endblock js %}

KDTFinalPJT/books/templates/books/review.html
{% extends 'base.html' %}
{% block content %}
  리뷰

  {% for book_review in book_reviews %}

    <a href="{% url 'books:review_detail' book_review.pk %}">
      <p>{{book_review.pk}}</p>
      <p>{{book_review.content}}</p>
      <p>{{book_review.created_at}}</p>
      <p><img src="{{book_review.image.url}}" alt=""></p>
    </a>

  {% endfor %}
{% endblock content %}

KDTFinalPJT/books/templates/books/review_detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <p>{{book_review.pk}}</p>
  <p>{{book_review.content}}</p>
  <p>{{book_review.created_at}}</p>
  <p><img src="{{book_review.image.url}}" alt=""></p>

  <a href="{% url "books:update" book_review.pk %}">수정</a>
  <a href="{% url "books:delete" book_review.pk %}">삭제</a>

  <form action="{% url 'books:comment_create' book_review.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <button type="submit">제출</button>
  </form>

  {% for comment in comments %}
    <p>{{comment.content}}</p>
  {% endfor %}
{% endblock content %}